export class API_END_POINTS  {
    static readonly COUNTER             = '/api/1.0/counter'
    static readonly LOGIN               = '/api/1.0/account/authenticate'
    static readonly LOGOUT              = '/api/1.0/account/logout'
    static readonly CHANGE_PASSWORD     = '/api/1.0/account/changepassword'
    static readonly FORGET_PASSWORD     = '/api/1.0/accountrecovery/forgetpassword'
    static readonly RESET_PASSWORD      = '/api/1.0/accountrecovery/resetpassword'
    static readonly USERS               = '/api/1.0/users'
    static readonly CHANGELOGS          = '/api/1.0/audit/changelog'
    static readonly USER_PROFILE        = '/api/1.0/users/profile'
    static readonly PROFILE_IMAGE       = '/dynamic/images/profile'
    static readonly ENQUIRY             = '/api/1.0/enquiries'
    static readonly ACCOUNTACTIVATION   = '/api/1.0/accountrecovery/accountactivation'
    static readonly NOTIFICATIONS       = '/api/1.0/notifiations'
}