export class API_END_POINTS  {
    static readonly COUNTER             = '/api/1.0/counter'
    static readonly CITY                = '/api/1.0/cities'
    static readonly STATE               = '/api/1.0/states'
    static readonly LOGIN               = '/api/1.0/account/authenticate'
    static readonly LOGOUT              = '/api/1.0/account/logout'
    static readonly CHANGE_PASSWORD     = '/api/1.0/account/changepassword'
    static readonly FORGET_PASSWORD     = '/api/1.0/accountrecovery/forgetpassword'
    static readonly RESET_PASSWORD      = '/api/1.0/accountrecovery/resetpassword'
    static readonly USERS               = '/api/1.0/users'
    static readonly TRACKHISTORIES      = '/api/1.0/trackhistories' 
    static readonly VENDORS             = '/api/1.0/vendors'
    static readonly CUSTOMERS           = '/api/1.0/customers' 
    static readonly RECEIPTBOOKS        = '/api/1.0/receiptbooks'    
    static readonly CONSIGNMENTS        = '/api/1.0/consignments'   
    static readonly CONSIGNMENTHISTORY  = '/api/1.0/consignmenthistories'
    static readonly USER_PROFILE        = '/api/1.0/users/profile'
    static readonly PROFILE_IMAGE       = '/dynamic/images/profile'
    static readonly ENQUIRY             = 'api/1.0/enquiries'
    static readonly AUTOCOMPLETES       = 'api/1.0/autocompletes'
    static readonly ACCOUNTACTIVATION   = '/api/1.0/accountrecovery/accountactivation'
    static readonly DASHBOARD           = '/api/1.0/dashboard'
    static readonly MANIFEST            = '/api/1.0/manifest'
}