export class ROUTE_END_POINTS  {
    static readonly ABOUT                = '/about'
    static readonly CONTACT              = '/contact'
    static readonly HOME                 = '/'
    static readonly LOGIN                = '/login'
    static readonly DASHBOARD            = '/dashboard'
    static readonly MANIFEST             = '/manifest'
    static readonly TRACKHISTORY         = '/trackhistory'
    static readonly USERS                = '/users'
    static readonly VENDORS              = '/vendors'
    static readonly CUSTOMERS            = '/customers'    
    static readonly CONSIGNMENT          = '/consignments'
    static readonly USER_PROFILE         = '/user/profile'
    static readonly CHANGE_PASSWORD      = '/change-password'
    static readonly FORGET_PASSWORD      = '/forget-password'
    static readonly PASSWORD_RECOVERY    = '/reset-password'
    static readonly ENQUIRY              = '/enquiries'
    static readonly ACCOUNTACTIVATION    = '/account-activation'
    static readonly VISITORS             = '/visitors'
    static readonly LOCATION             = '/location'
}