// <auto-generated/>

global using global::GenogramSystem.Core.Constants;
global using global::GenogramSystem.Core.Enumerations;
global using global::GenogramSystem.Core.Models.Entities.Audits;
global using global::GenogramSystem.Core.Models.Entities.Counters;
global using global::GenogramSystem.Core.Models.Entities.Enquiries;
global using global::GenogramSystem.Core.Models.Entities.Users;
global using global::GenogramSystem.Core.Models.Errors;
global using global::Microsoft.EntityFrameworkCore;
global using global::Microsoft.EntityFrameworkCore.Metadata.Builders;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Logging;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;
global using global::System.Linq.Expressions;
